### ISSUE TITLE
Getting error in Model

### ISSUE THREAD

**Issue by monali-2210** [AI4Bharat/IndicConformerASR#8]
> [NeMo E 2024-12-11 16:59:40 common:506] Model instantiation failed!
    Target class:#011nemo.collections.asr.models.hybrid_rnnt_ctc_bpe_models.EncDecHybridRNNTCTCBPEModel
    Error(s):#011'dir'
    Traceback (most recent call last):
      File "/usr/local/lib/python3.8/site-packages/nemo/core/classes/common.py", line 485, in from_config_dict
        instance = imported_cls(cfg=config, trainer=trainer)
      File "/usr/local/lib/python3.8/site-packages/nemo/collections/asr/models/hybrid_rnnt_ctc_bpe_models.py", line 51, in __init__
        self._setup_tokenizer(cfg.tokenizer)
      File "/usr/local/lib/python3.8/site-packages/nemo/collections/asr/parts/mixins/mixins.py", line 61, in _setup_tokenizer
        self._setup_monolingual_tokenizer(tokenizer_cfg)
      File "/usr/local/lib/python3.8/site-packages/nemo/collections/asr/parts/mixins/mixins.py", line 69, in _setup_monolingual_tokenizer
        self.tokenizer_dir = self.tokenizer_cfg.pop('dir')  # Remove tokenizer directory
    KeyError: 'dir'

> INFO:__main__:Failed to load with EncDecCTCModel, trying EncDecHybridRNNTCTCBPEModel: Missing key num_classes
    full_key: decoder.num_classes
    object_type=dict

    
    Getting this error while loading the model through this: `model = nemo_asr.models.EncDecCTCModel.restore_from(model_path)`

**Comment by wannasleepforlong** [comment]
I am facing the same issue It works in hi model but the output file still gives error
Error processing hindi_audio.wav: EncDecHybridRNNTCTCModel.transcribe() got an unexpected keyword argument 'language_id'

**Comment by ryback123** [comment]
@monali-2210 can you try it with `EncDecHybridRNNTCTCModel` instead of `EncDecCTCModel`.

**Comment by ryback123** [comment]
@wannasleepforlong the hindi model has a monolingual softmax and tokenizer, whereas the other language models have a multilingual softmax and tokenizer. The language id is not required for hindi, pass it only for the other languages. Try it once without passing the `language_id`.

**Comment by ryback123** [comment]
@monali-2210 actually I see it already tried using `EncDecHybridRNNTCTCModel` it in the error. Let me try and reproduce this on my system.

**Comment by ryback123** [comment]
@monali-2210 can you try this with `python=3.10.12`. You seem to be on `python=3.8`

**Comment by wannasleepforlong** [comment]
I am facing the same problem as @imoinuddin Nothing works except Hindi and shows error

**Comment by ryback123** [comment]
Can you all follow the steps shown in this notebook and see if it works?
https://colab.research.google.com/drive/1yG_WBXFQV3l11vjpM8fOsrhq6ojtpwKR?usp=sharing

**Comment by imoinuddin** [comment]
Tried it and doesn't work - fails when doing pip install -r requirements.txt :

```
ERROR: Cannot install -r requirements.txt (line 15), -r requirements.txt (line 17), -r requirements.txt (line 4), -r requirements.txt (line 5) and huggingface_hub==0.23 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested huggingface_hub==0.23
    transformers 4.40.0 depends on huggingface-hub<1.0 and >=0.19.3
    pyannote-audio 3.3.1 depends on huggingface-hub>=0.13.0
    datasets 2.21.0 depends on huggingface-hub>=0.21.2
    nemo-toolkit 1.23.0rc0 depends on huggingface_hub==0.23.2

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
```

**Comment by ryback123** [comment]
The requirements file would have been downloaded onto your colab, can you edit the requirements.txt file and change the `huggingface_hub` version to `0.23.2`

**Comment by imoinuddin** [comment]
That actually helped ! Fixed the issue.  Was able to get the inference to finally work. Thanks @ryback123  !

**Comment by wannasleepforlong** [comment]
Thanks a ton @ryback123 ! For people facing ``np.sctypes` was removed in the NumPy 2.0 release. Access dtypes explicitly instead `issue, just `python3 -m pip install "numpy==1.26.4 "`

**Comment by hammadfaheem** [comment]
try this 

import numpy as np

np.sctypes = {
    "int":   [np.int8, np.int16, np.int32, np.int64],
    "uint":  [np.uint8, np.uint16, np.uint32, np.uint64],
    "float": [np.float16, np.float32, np.float64],
    "complex": [np.complex64, np.complex128],
}
